import React from 'react';
import { Link } from 'react-router-dom';
import { categories } from '../data/categories';

const LandingPage = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-[#f0efff] via-[#e8e7ff] to-[#e0dfff]">
      {/* Hero Section */}
      <div className="container mx-auto px-4 py-16">
        <div className="text-center mb-20">
          <h1 className="text-6xl font-bold text-gray-900 mb-6">
            Welcome to <span className="text-blue-600">Quiz</span> Master
          </h1>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto leading-relaxed">
            Test your knowledge with our AI-powered quiz platform. Choose from various categories
            and difficulty levels to challenge yourself and learn something new!
          </p>
        </div>

        {/* Features Section */}
        <div className="grid md:grid-cols-3 gap-8 mb-24">
          <div className="bg-[#736ddf] p-8 rounded-2xl shadow-sm hover:shadow-md transition-all duration-300 border border-[#5f5ac4]">
            <div className="text-white mb-6">
              <svg className="w-12 h-12 mx-auto" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
              </svg>
            </div>
            <h3 className="text-xl font-semibold text-white mb-3">AI-Powered Questions</h3>
            <p className="text-gray-100 leading-relaxed">
              Dynamic questions generated by advanced AI technology for a unique experience every time.
            </p>
          </div>

          <div className="bg-[#736ddf] p-8 rounded-2xl shadow-sm hover:shadow-md transition-all duration-300 border border-[#5f5ac4]">
            <div className="text-white mb-6">
              <svg className="w-12 h-12 mx-auto" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
            <h3 className="text-xl font-semibold text-white mb-3">Timed Challenges</h3>
            <p className="text-gray-100 leading-relaxed">
              Test your knowledge under pressure with optional timer mode for an extra challenge.
            </p>
          </div>

          <div className="bg-[#736ddf] p-8 rounded-2xl shadow-sm hover:shadow-md transition-all duration-300 border border-[#5f5ac4]">
            <div className="text-white mb-6">
              <svg className="w-12 h-12 mx-auto" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
              </svg>
            </div>
            <h3 className="text-xl font-semibold text-white mb-3">Detailed Results</h3>
            <p className="text-gray-100 leading-relaxed">
              Get comprehensive feedback and review your answers to learn from your mistakes.
            </p>
          </div>
        </div>

        {/* Categories Preview */}
        <div className="mb-24">
          <h2 className="text-4xl font-bold text-center text-gray-900 mb-12">Available Categories</h2>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {categories.map((category) => (
              <div 
                key={category.id} 
                className="group bg-[#736ddf] rounded-2xl shadow-sm hover:shadow-md transition-all duration-300 border border-[#5f5ac4] overflow-hidden"
              >
                <div className="p-8">
                  <h3 className="text-2xl font-semibold text-white mb-4 group-hover:text-gray-100 transition-colors">
                    {category.name}
                  </h3>
                  <p className="text-gray-100 mb-6 leading-relaxed">
                    {category.description}
                  </p>
                  <Link
                    to={`/quiz-setup?category=${category.id}`}
                    className="inline-flex items-center px-6 py-3 bg-white text-[#736ddf] rounded-xl hover:bg-gray-100 hover:text-[#5f5ac4] transition-all duration-300 font-medium"
                  >
                    Start Quiz
                    <svg 
                      className="w-5 h-5 ml-2 group-hover:translate-x-1 transition-transform" 
                      fill="none" 
                      stroke="currentColor" 
                      viewBox="0 0 24 24"
                    >
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 7l5 5m0 0l-5 5m5-5H6" />
                    </svg>
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Call to Action */}
        <div className="text-center">
          <Link
            to="/quiz-setup"
            className="inline-flex items-center px-8 py-4 bg-blue-600 text-white text-xl font-semibold rounded-xl hover:bg-blue-700 transition-all duration-300 shadow-sm hover:shadow-md"
          >
            Start Your Quiz Journey
            <svg 
              className="w-6 h-6 ml-2" 
              fill="none" 
              stroke="currentColor" 
              viewBox="0 0 24 24"
            >
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 7l5 5m0 0l-5 5m5-5H6" />
            </svg>
          </Link>
        </div>
      </div>

      {/* Footer */}
      <footer className="mt-16 bg-[#736ddf]/10 backdrop-blur-sm py-12 border-t border-[#736ddf]/20">
        <div className="container mx-auto px-4">
          <div className="text-center">
            <p className="text-[#736ddf] mb-4 font-medium">Created with ❤️ by Ayush Sharma</p>
            <div className="flex justify-center space-x-6">
              <a
                href="https://github.com/sharmacodes13"
                target="_blank"
                rel="noopener noreferrer"
                className="text-[#736ddf] hover:text-[#5f5ac4] transition-colors"
              >
                GitHub
              </a>
              <a
                href="https://www.linkedin.com/in/ayush-sharma13/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-[#736ddf] hover:text-[#5f5ac4] transition-colors"
              >
                LinkedIn
              </a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage; 